[package]
name = "custom_tasksys"
version = "0.1.0"
edition = "2021"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

